package vsu.cs.tasks;

public enum LinkType {
    OUT_TUBE_IN_FITTING,
    OUT_WATER_CONSUMER_IN_FITTING,
    OUT_WATER_SOURCE_IN_FITTING,
    OUT_FITTING_IN_TUBE,
    OUT_FITTING_IN_DRAIN,
    OUT_FITTING_IN_WATER_CONSUMER,
}
